# Generated by Django 6.0.5 on 2026-09-26 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='e.g. 11', max_length=20)),
                ('gewerk', models.CharField(blank=True, help_text='e.g. Trockenbauarbeiten', max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('din276_group', models.CharField(blank=True, help_text='DIN 276 cost group, e.g. 390', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lv', to='projects.document')),
            ],
            options={
                'verbose_name': 'LV',
                'verbose_name_plural': 'LVs',
            },
        ),
        migrations.CreateModel(
            name='LVSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('lv', 'LV'), ('titel', 'Titel'), ('untertitel', 'Untertitel'), ('abschnitt', 'Abschnitt')], max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('page_start', models.PositiveIntegerField(blank=True, null=True)),
                ('lv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='extraction.lv')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='extraction.lvsection')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='LVItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Position number, e.g. 290', max_length=20)),
                ('oz', models.CharField(db_index=True, help_text='Ordnungszahl, e.g. 03.01.0290', max_length=60)),
                ('short_text', models.TextField(blank=True)),
                ('long_text', models.TextField(blank=True)),
                ('menge', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='quantity')),
                ('einheit', models.CharField(blank=True, max_length=20, verbose_name='unit')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='unit price (EP)')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='total price (GP)')),
                ('din276_group', models.CharField(blank=True, max_length=10)),
                ('confidence', models.FloatField(default=1.0)),
                ('page_start', models.PositiveIntegerField(blank=True, null=True)),
                ('page_end', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('pdf', 'PDF extraction'), ('gaeb', 'GAEB import'), ('manual', 'Manual entry')], default='pdf', max_length=10)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='extraction.lvsection')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
    ]
