# Generated by Django 6.0.5 on 2026-09-26 21:02

import django.db.models.deletion
import projects.models
import projects.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=projects.storage.PrivateStorage(), upload_to=projects.models.document_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('lv', 'Leistungsverzeichnis (BOQ)'), ('gaeb', 'GAEB file'), ('plan', 'Plan / drawing'), ('spec', 'Spec / other text'), ('other', 'Other')], default='lv', max_length=10)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('extracted', 'Extracted — ready for review'), ('manual_queue', 'Queued for manual processing'), ('approved', 'Approved'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('text_layer_ok', models.BooleanField(default=True)),
                ('run_judge', models.BooleanField(default=True, help_text='Run a second LLM as judge after extraction')),
                ('error_message', models.TextField(blank=True)),
                ('extraction_report', models.JSONField(blank=True, default=dict, help_text='Parser/LLM stats and judge notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.documentset')),
            ],
            options={
                'ordering': ['doc_type', 'original_filename'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address / site')),
                ('client_name', models.CharField(blank=True, max_length=255, verbose_name='client (Bauherr)')),
                ('architect', models.CharField(blank=True, max_length=255, verbose_name='planning / architect')),
                ('bid_deadline', models.DateTimeField(blank=True, null=True, verbose_name='bid deadline')),
                ('execution_period', models.CharField(blank=True, max_length=255, verbose_name='execution period')),
                ('submission_place', models.CharField(blank=True, max_length=255, verbose_name='submission place (Abgabeort)')),
                ('notes', models.TextField(blank=True)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='documentset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sets', to='projects.project'),
        ),
        migrations.AddConstraint(
            model_name='documentset',
            constraint=models.UniqueConstraint(fields=('project', 'version'), name='unique_set_version'),
        ),
    ]
