# Generated by Django 6.0.5 on 2026-09-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('auto', 'Auto-detect'), ('lv', 'Leistungsverzeichnis (BOQ)'), ('gaeb', 'GAEB file'), ('plan', 'Plan / drawing'), ('spec', 'Spec / other text'), ('other', 'Other')], default='auto', max_length=10),
        ),
    ]
