# Generated by Django 6.0.5 on 2026-09-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_document_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source_url',
            field=models.URLField(blank=True, help_text='Where this tender was found (e.g. berlin.de notice page)', verbose_name='source URL'),
        ),
    ]
