# Generated by Django 6.0.5 on 2026-09-27 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extraction', '0001_initial'),
        ('projects', '0002_alter_document_doc_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('trade_codes', models.CharField(blank=True, help_text='DIN 276 groups or trade labels, comma-separated', max_length=255)),
                ('regions', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='provider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('withdrawn', 'Withdrawn')], default='draft', max_length=12)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='projects.project')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='bidding.provider')),
            ],
            options={
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='unit price (EP)')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bidding.bid')),
                ('lv_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_items', to='extraction.lvitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bid', 'lv_item'), name='unique_biditem_per_lvitem')],
            },
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(fields=('project', 'provider'), name='unique_bid_per_provider'),
        ),
    ]
